const currencies = [
    { value: 'EUR', label: 'EUR' },
    { value: 'USD', label: 'USD' },
    { value: 'AUD', label: 'AUD' },
    { value: 'BGN', label: 'BGN' },
    { value: 'BRL', label: 'BRL' },
    { value: 'CAD', label: 'CAD' },
    { value: 'CHF', label: 'CHF' },
    { value: 'CNY', label: 'CNY' },
    { value: 'CZK', label: 'CZK' },
    { value: 'DKK', label: 'DKK' },
    { value: 'GBP', label: 'GBP' },
    { value: 'HKD', label: 'HKD' },
    { value: 'HRK', label: 'HRK' },
    { value: 'HUF', label: 'HUF' },
    { value: 'IDR', label: 'IDR' },
    { value: 'ILS', label: 'ILS' },
    { value: 'INR', label: 'INR' },
    { value: 'JPY', label: 'JPY' },
    { value: 'KRW', label: 'KRW' },
    { value: 'MXN', label: 'MXN' },
    { value: 'MYR', label: 'MYR' },
    { value: 'NOK', label: 'NOK' },
    { value: 'NZD', label: 'NZD' },
    { value: 'PHP', label: 'PHP' },
    { value: 'PLN', label: 'PLN' },
    { value: 'RON', label: 'RON' },
    { value: 'RUB', label: 'RUB' },
    { value: 'SEK', label: 'SEK' },
    { value: 'SGD', label: 'SGD' },
    { value: 'THB', label: 'THB' },
    { value: 'TRY', label: 'TRY' },
    { value: 'ZAR', label: 'ZAR' },
];

const durations = [
    { value: '3 days', label: '3 days' },
    { value: '1 week', label: '1 week' },
    { value: '2 weeks', label: '2 weeks' },
    { value: '3 weeks', label: '3 weeks' },
    { value: '5 weeks', label: '5 weeks' },
    { value: '10 weeks', label: '10 weeks' },
    { value: '25 weeks', label: '25 weeks' },
];

export {
    currencies,
    durations,
};
